spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/horse_manager
  jackson:
    default-property-inclusion: non_null
jwt:
  secret: "vanhieu"
  expirationDateInMs: 600000
  refreshExpirationDateInMs: 1200000


